apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: demo-client
    spec:
      containers:
        - name: demo-client
          image: 10.3.98.241/demo/demo-client
          ports:
            - containerPort: 2001
#           resources:
#             limits:
#             cpu: 0.5
#             memory: 512Mi
#          volumeMounts:
#            - mountPath: /sceo-log/log
#              name: go-logs
#      volumes:
#      - name: go-logs
#        hostPath:
#          path: /sceo-log/log