apiVersion: v1
kind: Service
metadata:
  name: demo-provider-service
spec:
  type: NodePort
  ports:
    - port: 2000
      nodePort: 32000
      targetPort: 2000
      protocol: TCP
  selector:
    name: demo-provider