apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-provider-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: demo-provider
    spec:
      containers:
        - name: demo-provider
          image: 10.3.98.241/demo/demo-provider
          ports:
            - containerPort: 2000
#          volumeMounts:
#            - mountPath: /sceo-log/log
#              name: go-logs
#      volumes:
#      - name: go-logs
#        hostPath:
#          path: /sceo-log/log